### PR TITLE
add indep seminar

### PR DESCRIPTION
**Pull request by mzgubic**

### CODE REVIEW

**Comment by hushchyn-mikhail** [comment]
Hi Miha,

You use different shades of red. I am not sure, that they will be recognizable on the projector.
It is reasonable to use different colors.

**Comment by mzgubic** [comment]
Hi Mikhail,

Thanks for taking a look at the notebook! I've used the same color scheme on a few projectors already and there were no complaints so far. Would it be possible to test it on this projector during the lunch break perhaps? - I am happy to change it if it isn't legible.

Cheers,
Miha

**Comment by hushchyn-mikhail** [comment]
Dear Miha,

Let me know when your notebook will be finished and I will merge the pull request and add a link for colab.

**Comment by mzgubic** [comment]
Hi Mikhail,

I've changed the tomato to yellow in critical cases, thanks again for checking :)

Cheers,
Miha

**Pull request merged**
